<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //   //Here in a fetchData function we passed a callback function which will be executed after asynn process.
      //   function fetchData(cb) {
      //     let data;
      //     setTimeout(() => {
      //       data = { pCode: 1001, pName: "Orange" };
      //       cb(data);
      //     }, 2000);
      //   }
      //   function displayData(data) {
      //     console.log(data);
      //     console.log("end here");
      //   }
      //   //to come out of asynchronous process callback comes into the picture, in a callback function we pass another function which will be exectuted after asyn process as we have seen in example of setTimeout()
      //   console.log("starts here");
      //   fetchData((data) => {
      //     displayData(data);
      //   });

      //take another simple example of squaring a number with asynchronous process

      //   function cSqr(n, cb) {
      //     setTimeout(() => {
      //       cb(n * n);
      //     }, 2000);
      //   }
      //   //here he problem of callback hell or pyramind of doom occur
      //   cSqr(2, (res) => {
      //     console.log(res);
      //     cSqr(res, (res1) => {
      //       console.log(res1);
      //       cSqr(res1, (res3) => {
      //         console.log(res3);
      //         cSqr(res3, (res4) => {
      //           console.log(res4);
      //         });
      //       });
      //     });
      //   });

      //

      //   function fetchData(cb) {
      //     return new Promise((resolve, reject) => {
      //       setTimeout(() => {
      //         let data = { pCode: 1001, pName: "Orange" };
      //         resolve(data);
      //       }, 2000);
      //     });
      //   }
      //   console.log("Program starts");
      //   fetchData()
      //     .then((data) => {
      //       console.log(data);
      //     })
      //     .catch((err) => {
      //       console.log("Error " + err);
      //     })
      //     .finally(() => {
      //       console.log("Program finally ends");
      //     });

      //Promisification of sqaure function

      const cSqr = (a) => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve(a * a);
          }, 1000);
        });
      };

      cSqr(2)
        .then((res) => {
          console.log(res);
          return cSqr(res);
        })
        .then((res1) => {
          console.log(res1);
          return cSqr(res1); //You have to return the promise after chaining it.
        })
        .then((res3) => {
          console.log(res3);
        })
        .catch((err) => {
          console.log("Error " + err);
        })
        .finally(() => {
          console.log("Finishing process");
        });
      //simple syntax of promise
      console.log("simple syntax of promise");
    </script>
  </body>
</html>
